#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Training.Droid.Resource", IsApplication=true)]

namespace Xamarin.Training.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Xamarin.Training.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Xamarin.Training.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Xamarin.Training.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_cart_product = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int linlayoutborder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int addToWishlist = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int btnRegMgmt = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int button1 = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int buttonZxingFlash = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int contentFrame = 2131099673;
			
			// aapt resource value: 0x7f06000b
			public const int imgDollar = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int imgvProdadd = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int imgvProduct = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int linearLayout1 = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout2 = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int lvProdList = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int myButton = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int myTxt = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int productList = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int productName = 2131099664;
			
			// aapt resource value: 0x7f060002
			public const int scanBtn = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int searchBtn = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int textView1 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int textView2 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int textView3 = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int tr = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int txtAddToCart = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int txtProdName = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int txtProdPrice = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int txtProdQty = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int txtProdSearch = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProductList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProductListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProductListScan = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RegistryListItemLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RegistryManagement = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ZxingOverlay = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int button = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_title = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int no = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int yes = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int HomeButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Mono_Android_Theme_Splash = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int listviewTheme = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
